---
- name: Create ~jumbotron/.irssi directories
  file:
    path: '~jumbotron/{{ item }}'
    state: directory
    owner: jumbotron
    group: users
    mode: 0755
  with_items:
  - .irssi
  - .irssi/scripts
  - .irssi/scripts/autorun

- name: Configure irssi
  copy:
    dest: '~jumbotron/.irssi/config'
    src: irssi.config
    owner: jumbotron
    group: users
    mode: 0644

- name: Add autorun link for custom irssi plugins
  file:
    path: '~jumbotron/.irssi/scripts/autorun/{{item}}'
    src: '../../../jumbotron/{{item}}'
    state: link
  with_items:
  - jumbowatch.pl
  - Jumbochatter.pl

# vim: set ts=2 sw=2 et:
